"""Resolve QuestLog catalog rows to Elden Ring save inventory IDs."""

from __future__ import annotations

from core.catalog_sync import CatalogStore

_ARMOR_BASE = 0x10000000
_TALISMAN_BASE = 0x20000000
_MAGIC_BASE = 0x40000000

_CACHE: dict[str, dict[str, tuple[str, str]]] = {}

_LABELS = {
    "vanilla": {
        "weapon": "armament",
        "armor": "armor",
        "talisman": "talisman",
        "spell": "magic",
    },
    "reforged": {
        "weapon": "ERR: Weapons",
        "armor": "ERR: Armor",
        "talisman": "ERR: Talismans",
        "spell": "ERR: Magic",
    },
}

_DATASET_BY_MODE = {
    "vanilla": "vanilla_calculations",
    "reforged": "err_calculations",
}

_SPELL_RESOURCE_BY_MODE = {
    "vanilla": "spells_vanilla",
    "reforged": "spells_err",
}

_ERR_EXTRACTED_ITEM_IDS = {
    # Extracted from ERR v2.2.9.5 English item FMGs generated by WitchyBND
    # from msg/engus/item_dlc02.msgbnd.dcx. Weapon FMG IDs are save IDs;
    # talisman save IDs are 0x20000000 + the FMG ID.
    "0011DA50": ("ERR: Weapons", "Night's Edge"),
    "00200B20": ("ERR: Weapons", "Marionette Short Sword"),
    "0022CA40": ("ERR: Weapons", "Coilheart"),
    "004D83C0": ("ERR: Weapons", "Immortal Coil"),
    "006D40C0": ("ERR: Weapons", "Avionette Scimitars"),
    "00F646E0": ("ERR: Weapons", "Marionette Spiked Spear"),
    "01147D40": ("ERR: Weapons", "Avionette Pig Sticker"),
    "0114CB60": ("ERR: Weapons", "Dragonscale Halberd"),
    "015F96A4": ("ERR: Weapons", "Rotten Duelist Greataxe"),
    "01613DB0": ("ERR: Weapons", "Rotten Duelist Greataxe"),
    "01FABE90": ("ERR: Weapons", "Dark Glintstone Staff"),
    "01FC1E20": ("ERR: Weapons", "Snow Witch Scepter"),
    "200013CE": ("ERR: Talismans", "Assassin's Viridian Dagger"),
}


def _hex_item_id(value: int) -> str:
    return f"{int(value):08X}"


def _as_int(value) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _merge_weapon_lookup(lookup: dict[str, tuple[str, str]], weapons: dict, label: str) -> None:
    if not isinstance(weapons, dict):
        return
    for name, variants in weapons.items():
        if not name or not isinstance(variants, dict):
            continue
        for variant in variants.values():
            if not isinstance(variant, dict):
                continue
            regulation_id = _as_int(variant.get("regulation_id"))
            if regulation_id is not None:
                lookup[_hex_item_id(regulation_id)] = (label, str(name))


def _merge_simple_regulation_lookup(
    lookup: dict[str, tuple[str, str]],
    rows: dict,
    label: str,
    base: int,
) -> None:
    if not isinstance(rows, dict):
        return
    for name, row in rows.items():
        if not name or not isinstance(row, dict):
            continue
        regulation_id = _as_int(row.get("regulation_id"))
        if regulation_id is not None:
            lookup[_hex_item_id(base + regulation_id)] = (label, str(name))


def _merge_spell_lookup(
    lookup: dict[str, tuple[str, str]],
    store: CatalogStore,
    resource: str,
    label: str,
) -> None:
    try:
        payload = store.load_live(resource)
    except Exception:
        return
    spells = payload.get("spells") if isinstance(payload, dict) else None
    if not isinstance(spells, list):
        return
    for spell in spells:
        if not isinstance(spell, dict):
            continue
        name = str(spell.get("name") or "").strip()
        raw_id = _as_int(spell.get("id"))
        if not name or raw_id is None:
            continue
        item_id = raw_id if raw_id >= _MAGIC_BASE else raw_id + _MAGIC_BASE
        lookup[_hex_item_id(item_id)] = (label, name)


def build_lookup(mode: str, store: CatalogStore | None = None) -> dict[str, tuple[str, str]]:
    """Return save item ID -> (category label, catalog name) for a game mode."""
    normalized_mode = "reforged" if mode in {"err", "reforged"} else "vanilla"
    store = store or CatalogStore()
    labels = _LABELS[normalized_mode]
    lookup: dict[str, tuple[str, str]] = {}

    if normalized_mode == "reforged":
        try:
            vanilla_dataset = store.load("vanilla_calculations")
        except Exception:
            vanilla_dataset = None
        vanilla_payload = vanilla_dataset.get("payload") if isinstance(vanilla_dataset, dict) else None
        if isinstance(vanilla_payload, dict):
            _merge_weapon_lookup(lookup, vanilla_payload.get("weapons"), labels["weapon"])

    try:
        dataset = store.load(_DATASET_BY_MODE[normalized_mode])
    except Exception:
        dataset = None
    payload = dataset.get("payload") if isinstance(dataset, dict) else None
    if isinstance(payload, dict):
        _merge_weapon_lookup(lookup, payload.get("weapons"), labels["weapon"])
        _merge_simple_regulation_lookup(lookup, payload.get("armor"), labels["armor"], _ARMOR_BASE)
        _merge_simple_regulation_lookup(lookup, payload.get("talismans"), labels["talisman"], _TALISMAN_BASE)

    _merge_spell_lookup(lookup, store, _SPELL_RESOURCE_BY_MODE[normalized_mode], labels["spell"])
    if normalized_mode == "reforged":
        lookup.update(_ERR_EXTRACTED_ITEM_IDS)
    return lookup


def get_lookup(mode: str) -> dict[str, tuple[str, str]]:
    normalized_mode = "reforged" if mode in {"err", "reforged"} else "vanilla"
    if normalized_mode not in _CACHE:
        _CACHE[normalized_mode] = build_lookup(normalized_mode)
    return _CACHE[normalized_mode]
